/**
 * The moderation word lexicon — deliberately kept separate from
 * profanityFilter.js's matching logic, per the explicit "do not use
 * a global bad-word array inside JSX / keep the list in a dedicated
 * module" requirement.
 *
 * IMPORTANT, STATED HONESTLY: this starter lexicon contains only a
 * small set of generic, mild English profanity terms, demonstrating
 * the real matching mechanism (case-insensitivity, spacing/repeated-
 * character evasion, severity tiers) — it does NOT include slurs or
 * severe hate/harassment terms. I'm not compiling that list myself;
 * it's something you should populate and review directly, since
 * getting a real-world slur/harassment lexicon right requires
 * judgment calls (regional slang, reclaimed terms, context) that
 * shouldn't be made unilaterally by whoever wires up the filter.
 * The architecture below (severity tiers, easy to extend, one term
 * per line) is built to make that population straightforward once
 * you're ready to do it.
 */

export const SEVERITY = {
  LOW: 'low',       // mild profanity — mask only
  MEDIUM: 'medium',  // insults / harassment language — mask + report signal
  HIGH: 'high'       // threats / hate / severe abuse — flag for moderation review, do not just mask
}

/**
 * Each entry: { term, severity }. `term` is the canonical, lowercase,
 * space-free form — profanityFilter.js's normalization strips spacing/
 * punctuation/repeated characters before comparing, so entries here
 * don't need every possible spelling variant listed separately.
 */
export const PROFANITY_TERMS = [
  { term: 'damn', severity: SEVERITY.LOW },
  { term: 'hell', severity: SEVERITY.LOW },
  { term: 'crap', severity: SEVERITY.LOW },
  { term: 'shit', severity: SEVERITY.LOW },
  { term: 'ass', severity: SEVERITY.LOW },
  { term: 'bitch', severity: SEVERITY.MEDIUM },
  { term: 'bastard', severity: SEVERITY.MEDIUM },
  { term: 'idiot', severity: SEVERITY.LOW },
  { term: 'stupid', severity: SEVERITY.LOW },
  // Added following a confirmed live-test report: 'madarchod' was
  // submitted through the real composer and posted unmasked. Root
  // cause was twofold — this term was never in the lexicon at all
  // (fixed here), AND the filter was never wired into any actual
  // write path (a separate, deeper issue — see this fix's own
  // report). Common Hindi/Urdu abusive terms below, same honest
  // caveat as the note above: this is not a comprehensive
  // multilingual lexicon, just the specifically reported gap plus
  // immediately adjacent common terms.
  { term: 'madarchod', severity: SEVERITY.HIGH },
{ term: 'behenchod', severity: SEVERITY.HIGH },
{ term: 'bhosdike', severity: SEVERITY.HIGH },
{ term: 'bhosdiwala', severity: SEVERITY.HIGH },
{ term: 'bhosdichod', severity: SEVERITY.HIGH },
{ term: 'chut', severity: SEVERITY.HIGH },
{ term: 'chutiya', severity: SEVERITY.MEDIUM },
{ term: 'chutiyapa', severity: SEVERITY.MEDIUM },
{ term: 'chutiyapanti', severity: SEVERITY.MEDIUM },
{ term: 'randi', severity: SEVERITY.HIGH },
{ term: 'rand', severity: SEVERITY.HIGH },
{ term: 'gandu', severity: SEVERITY.MEDIUM },
{ term: 'gaand', severity: SEVERITY.HIGH },
{ term: 'gaandu', severity: SEVERITY.MEDIUM },
{ term: 'gaandfat', severity: SEVERITY.HIGH },
{ term: 'gaandmara', severity: SEVERITY.HIGH },
{ term: 'gaandmar', severity: SEVERITY.HIGH },
{ term: 'lauda', severity: SEVERITY.HIGH },
{ term: 'laude', severity: SEVERITY.HIGH },
{ term: 'laudu', severity: SEVERITY.HIGH },
{ term: 'lund', severity: SEVERITY.HIGH },
{ term: 'loda', severity: SEVERITY.HIGH },
{ term: 'lodu', severity: SEVERITY.HIGH },
{ term: 'lavde', severity: SEVERITY.HIGH },
{ term: 'lavda', severity: SEVERITY.HIGH },
{ term: 'lavdya', severity: SEVERITY.HIGH },
{ term: 'jhatu', severity: SEVERITY.MEDIUM },
{ term: 'jhaatu', severity: SEVERITY.MEDIUM },
{ term: 'jhant', severity: SEVERITY.MEDIUM },
{ term: 'jhantoo', severity: SEVERITY.MEDIUM },
{ term: 'harami', severity: SEVERITY.MEDIUM },
{ term: 'haraami', severity: SEVERITY.MEDIUM },
{ term: 'haramkhor', severity: SEVERITY.HIGH },
{ term: 'haramkhor', severity: SEVERITY.HIGH },
{ term: 'kamina', severity: SEVERITY.MEDIUM },
{ term: 'kameena', severity: SEVERITY.MEDIUM },
{ term: 'kamine', severity: SEVERITY.MEDIUM },
{ term: 'kamini', severity: SEVERITY.MEDIUM },
{ term: 'saala', severity: SEVERITY.LOW },
{ term: 'saale', severity: SEVERITY.LOW },
{ term: 'saali', severity: SEVERITY.LOW },
{ term: 'saale kutte', severity: SEVERITY.MEDIUM },
{ term: 'kutte', severity: SEVERITY.LOW },
{ term: 'kutta', severity: SEVERITY.LOW },
{ term: 'kutiya', severity: SEVERITY.MEDIUM },
{ term: 'kutti', severity: SEVERITY.MEDIUM },
{ term: 'suar', severity: SEVERITY.MEDIUM },
{ term: 'suwar', severity: SEVERITY.MEDIUM },
{ term: 'suvar', severity: SEVERITY.MEDIUM },
{ term: 'gadha', severity: SEVERITY.LOW },
{ term: 'gadha sala', severity: SEVERITY.MEDIUM },
{ term: 'ullu', severity: SEVERITY.LOW },
{ term: 'ullu ka pattha', severity: SEVERITY.MEDIUM },
{ term: 'ullu ke pathe', severity: SEVERITY.MEDIUM },
{ term: 'bewakoof', severity: SEVERITY.LOW },
{ term: 'bewaqoof', severity: SEVERITY.LOW },
{ term: 'bevkoof', severity: SEVERITY.LOW },
{ term: 'pagal', severity: SEVERITY.LOW },
{ term: 'paagal', severity: SEVERITY.LOW },
{ term: 'pagla', severity: SEVERITY.LOW },
{ term: 'pagli', severity: SEVERITY.LOW },
{ term: 'nalayak', severity: SEVERITY.LOW },
{ term: 'nikamma', severity: SEVERITY.LOW },
{ term: 'nikammi', severity: SEVERITY.LOW },
{ term: 'bakchod', severity: SEVERITY.MEDIUM },
{ term: 'bakchodi', severity: SEVERITY.LOW },
{ term: 'bakchodhi', severity: SEVERITY.LOW },
{ term: 'bakchodi kar', severity: SEVERITY.LOW },
{ term: 'badtameez', severity: SEVERITY.LOW },
{ term: 'badtameez insaan', severity: SEVERITY.LOW },
{ term: 'besaram', severity: SEVERITY.MEDIUM },
{ term: 'besharam', severity: SEVERITY.MEDIUM },
{ term: 'beghairat', severity: SEVERITY.MEDIUM },
{ term: 'gairatheen', severity: SEVERITY.MEDIUM },
{ term: 'zaleel', severity: SEVERITY.MEDIUM },
{ term: 'kamjat', severity: SEVERITY.MEDIUM },
{ term: 'neech', severity: SEVERITY.MEDIUM },
{ term: 'ghatiya', severity: SEVERITY.MEDIUM },
{ term: 'ghatiya aadmi', severity: SEVERITY.MEDIUM },
{ term: 'ghatiya insaan', severity: SEVERITY.MEDIUM },
{ term: 'nalayak aadmi', severity: SEVERITY.LOW },
{ term: 'nikal yahan se', severity: SEVERITY.LOW },
{ term: 'dimaag kharab', severity: SEVERITY.LOW },
{ term: 'dimaag se paidal', severity: SEVERITY.MEDIUM },
{ term: 'akhand chutiya', severity: SEVERITY.HIGH },
{ term: 'ultimate chutiya', severity: SEVERITY.HIGH },
{ term: 'maha chutiya', severity: SEVERITY.HIGH },
{ term: 'number one chutiya', severity: SEVERITY.MEDIUM },
{ term: 'chutiye', severity: SEVERITY.MEDIUM },
{ term: 'chutiyye', severity: SEVERITY.MEDIUM },
{ term: 'chuteya', severity: SEVERITY.MEDIUM },
{ term: 'chutia', severity: SEVERITY.MEDIUM },
{ term: 'chutiyaa', severity: SEVERITY.MEDIUM },
{ term: 'chutiyo', severity: SEVERITY.MEDIUM },
{ term: 'madarchod saala', severity: SEVERITY.HIGH },
{ term: 'madarchuda', severity: SEVERITY.HIGH },
{ term: 'madarchode', severity: SEVERITY.HIGH },
{ term: 'madar chod', severity: SEVERITY.HIGH },
{ term: 'madar***', severity: SEVERITY.HIGH },
{ term: 'mc', severity: SEVERITY.HIGH },
{ term: 'm.c', severity: SEVERITY.HIGH },
{ term: 'm c', severity: SEVERITY.HIGH },
{ term: 'behen chod', severity: SEVERITY.HIGH },
{ term: 'behenchoda', severity: SEVERITY.HIGH },
{ term: 'behenchode', severity: SEVERITY.HIGH },
{ term: 'bc', severity: SEVERITY.HIGH },
{ term: 'b.c', severity: SEVERITY.HIGH },
{ term: 'b c', severity: SEVERITY.HIGH },
{ term: 'bhosdika', severity: SEVERITY.HIGH },
{ term: 'bhosdike saale', severity: SEVERITY.HIGH },
{ term: 'bhosdi', severity: SEVERITY.HIGH },
{ term: 'bhosda', severity: SEVERITY.HIGH },
{ term: 'bhosdiwale', severity: SEVERITY.HIGH },
{ term: 'gand mara', severity: SEVERITY.HIGH },
{ term: 'gandmara', severity: SEVERITY.HIGH },
{ term: 'gandmar', severity: SEVERITY.HIGH },
{ term: 'gand mein ja', severity: SEVERITY.HIGH },
{ term: 'gand phat gayi', severity: SEVERITY.MEDIUM },
{ term: 'gaand mein ja', severity: SEVERITY.HIGH },
{ term: 'gaand mein ghus', severity: SEVERITY.HIGH },
{ term: 'gaand ke', severity: SEVERITY.HIGH },
{ term: 'gaand ke baal', severity: SEVERITY.HIGH },
{ term: 'gand ke baal', severity: SEVERITY.HIGH },
{ term: 'gaand ka', severity: SEVERITY.HIGH },
{ term: 'gand chaat', severity: SEVERITY.HIGH },
{ term: 'gand chaatne wala', severity: SEVERITY.HIGH },
{ term: 'chut chaat', severity: SEVERITY.HIGH },
{ term: 'chut ka', severity: SEVERITY.HIGH },
{ term: 'chut ke', severity: SEVERITY.HIGH },
{ term: 'chut mein ja', severity: SEVERITY.HIGH },
{ term: 'launde', severity: SEVERITY.LOW },
{ term: 'launda', severity: SEVERITY.LOW },
{ term: 'laundiya', severity: SEVERITY.LOW },
{ term: 'lodu saala', severity: SEVERITY.HIGH },
{ term: 'laude lag gaye', severity: SEVERITY.MEDIUM },
{ term: 'laude ka', severity: SEVERITY.HIGH },
{ term: 'laude ke', severity: SEVERITY.HIGH },
{ term: 'lund ke', severity: SEVERITY.HIGH },
{ term: 'lund ka', severity: SEVERITY.HIGH },
{ term: 'lund chaat', severity: SEVERITY.HIGH },
{ term: 'lund pakad', severity: SEVERITY.HIGH },
{ term: 'lund fakir', severity: SEVERITY.MEDIUM },
{ term: 'randi ke', severity: SEVERITY.HIGH },
{ term: 'randi ka', severity: SEVERITY.HIGH },
{ term: 'randi ki aulaad', severity: SEVERITY.HIGH },
{ term: 'randi ke bacche', severity: SEVERITY.HIGH },
{ term: 'harami saala', severity: SEVERITY.HIGH },
{ term: 'haramzada', severity: SEVERITY.HIGH },
{ term: 'haramjaada', severity: SEVERITY.HIGH },
{ term: 'haramzade', severity: SEVERITY.HIGH },
{ term: 'haramzaada', severity: SEVERITY.HIGH },
{ term: 'haramkhor saala', severity: SEVERITY.HIGH },
{ term: 'kamine saale', severity: SEVERITY.MEDIUM },
{ term: 'kamina saala', severity: SEVERITY.MEDIUM },
{ term: 'kutte ka pilla', severity: SEVERITY.MEDIUM },
{ term: 'kutte ki aulaad', severity: SEVERITY.HIGH },
{ term: 'kutta sala', severity: SEVERITY.MEDIUM },
{ term: 'suar ki aulaad', severity: SEVERITY.HIGH },
{ term: 'suar ke bacche', severity: SEVERITY.HIGH },
{ term: 'jaanwar', severity: SEVERITY.LOW },
{ term: 'jaanwar saala', severity: SEVERITY.MEDIUM },
{ term: 'keeda', severity: SEVERITY.LOW },
{ term: 'gandi aulaad', severity: SEVERITY.MEDIUM },
{ term: 'gandi soch', severity: SEVERITY.LOW },
{ term: 'ghatiya aadmi', severity: SEVERITY.MEDIUM },
{ term: 'ghatiya aurat', severity: SEVERITY.MEDIUM },
{ term: 'do kaudi ka', severity: SEVERITY.MEDIUM },
{ term: 'do kaudi ka aadmi', severity: SEVERITY.MEDIUM },
{ term: 'faltu aadmi', severity: SEVERITY.LOW },
{ term: 'faltu insaan', severity: SEVERITY.LOW },
{ term: 'bakwaas aadmi', severity: SEVERITY.LOW },
{ term: 'bakwaas insaan', severity: SEVERITY.LOW },
{ term: 'bakwaas kar', severity: SEVERITY.LOW },
{ term: 'chup kar', severity: SEVERITY.LOW },
{ term: 'chup be', severity: SEVERITY.LOW },
{ term: 'chup saale', severity: SEVERITY.MEDIUM },
{ term: 'abe saale', severity: SEVERITY.LOW },
{ term: 'abe chutiye', severity: SEVERITY.MEDIUM },
{ term: 'oye chutiye', severity: SEVERITY.MEDIUM },
{ term: 'oye gandu', severity: SEVERITY.MEDIUM },
{ term: 'abe gandu', severity: SEVERITY.MEDIUM },
{ term: 'abe harami', severity: SEVERITY.MEDIUM },
{ term: 'abe kamine', severity: SEVERITY.MEDIUM },
{ term: 'besharam saala', severity: SEVERITY.MEDIUM },
{ term: 'beghairat saala', severity: SEVERITY.MEDIUM },
{ term: 'nalayak saala', severity: SEVERITY.MEDIUM },
{ term: 'nikamma saala', severity: SEVERITY.MEDIUM },
{ term: 'jhantu saala', severity: SEVERITY.MEDIUM },
{ term: 'jhatu saala', severity: SEVERITY.MEDIUM },
{ term: 'bakchod saala', severity: SEVERITY.MEDIUM },
{ term: 'bakchod aadmi', severity: SEVERITY.MEDIUM },
{ term: 'bakchod insaan', severity: SEVERITY.MEDIUM },
{ term: 'panauti', severity: SEVERITY.LOW },
{ term: 'panauti saala', severity: SEVERITY.MEDIUM },
{ term: 'manhoos', severity: SEVERITY.LOW },
{ term: 'manhoos saala', severity: SEVERITY.MEDIUM },
{ term: 'kharab dimaag', severity: SEVERITY.LOW },
{ term: 'dimaag nahi hai', severity: SEVERITY.LOW },
{ term: 'akal ka dushman', severity: SEVERITY.LOW },
{ term: 'akal se paidal', severity: SEVERITY.MEDIUM },
{ term: 'akal ka andha', severity: SEVERITY.MEDIUM },
{ term: 'andha hai kya', severity: SEVERITY.LOW },
{ term: 'khadoos', severity: SEVERITY.LOW },
{ term: 'lafanga', severity: SEVERITY.MEDIUM },
{ term: 'lafange', severity: SEVERITY.MEDIUM },
{ term: 'awara', severity: SEVERITY.LOW },
{ term: 'awara saala', severity: SEVERITY.MEDIUM },
{ term: 'nalayak kutta', severity: SEVERITY.MEDIUM },
{ term: 'harami kutta', severity: SEVERITY.HIGH },
{ term: 'kamina kutta', severity: SEVERITY.MEDIUM },
{ term: 'chutiya kutta', severity: SEVERITY.HIGH },
{ term: 'gandu saala', severity: SEVERITY.MEDIUM },
{ term: 'gandu kutta', severity: SEVERITY.HIGH },
{ term: 'lodu kutta', severity: SEVERITY.HIGH },
{ term: 'jhantu kutta', severity: SEVERITY.MEDIUM },
{ term: 'bhosdika saala', severity: SEVERITY.HIGH },
{ term: 'madarchod saala', severity: SEVERITY.HIGH },
{ term: 'behenchod saala', severity: SEVERITY.HIGH },
{ term: 'haramzada saala', severity: SEVERITY.HIGH },
{ term: 'randi ka baccha', severity: SEVERITY.HIGH },
{ term: 'randi ke bacche', severity: SEVERITY.HIGH },
{ term: 'gand ke bacche', severity: SEVERITY.HIGH },
{ term: 'gaand ke bacche', severity: SEVERITY.HIGH },
{ term: 'chut ke bacche', severity: SEVERITY.HIGH },
{ term: 'bhosdi ke bacche', severity: SEVERITY.HIGH },
{ term: 'laude ke bacche', severity: SEVERITY.HIGH },
{ term: 'lund ke bacche', severity: SEVERITY.HIGH },
{ term: 'kamina aadmi', severity: SEVERITY.MEDIUM },
{ term: 'kamini aurat', severity: SEVERITY.MEDIUM },
{ term: 'harami aadmi', severity: SEVERITY.MEDIUM },
{ term: 'harami aurat', severity: SEVERITY.MEDIUM },
{ term: 'besharam aadmi', severity: SEVERITY.MEDIUM },
{ term: 'besharam aurat', severity: SEVERITY.MEDIUM },
{ term: 'ghatiya banda', severity: SEVERITY.MEDIUM },
{ term: 'ghatiya bandi', severity: SEVERITY.MEDIUM },
{ term: 'ghatiya insaan', severity: SEVERITY.MEDIUM },
{ term: 'nikal be', severity: SEVERITY.LOW },
{ term: 'chal nikal', severity: SEVERITY.LOW },
{ term: 'bhaag yahan se', severity: SEVERITY.LOW },
{ term: 'dafa ho', severity: SEVERITY.LOW },
{ term: 'dafa ho ja', severity: SEVERITY.LOW },
{ term: 'bakwass band kar', severity: SEVERITY.LOW },
{ term: 'bakwas band kar', severity: SEVERITY.LOW },
{ term: 'bakwaas band kar', severity: SEVERITY.LOW },
{ term: 'teri aukaat', severity: SEVERITY.MEDIUM },
{ term: 'aukaat mein reh', severity: SEVERITY.MEDIUM },
{ term: 'aukaat kya hai', severity: SEVERITY.MEDIUM },
{ term: 'teri aukaat kya hai', severity: SEVERITY.MEDIUM },
{ term: 'shakal dekh apni', severity: SEVERITY.LOW },
{ term: 'shakal mat dikha', severity: SEVERITY.LOW },
{ term: 'munh band kar', severity: SEVERITY.LOW },
{ term: 'munh tod dunga', severity: SEVERITY.HIGH },
{ term: 'maar khaega', severity: SEVERITY.MEDIUM },
{ term: 'maar khaayega', severity: SEVERITY.MEDIUM },
{ term: 'maar khaogi', severity: SEVERITY.MEDIUM },
{ term: 'maar khaoge', severity: SEVERITY.MEDIUM },
{ term: 'ullu ka pattha', severity: SEVERITY.MEDIUM },
{ term: 'ullu ka puththa', severity: SEVERITY.MEDIUM },
{ term: 'gadha kahin ka', severity: SEVERITY.LOW },
{ term: 'gadhe', severity: SEVERITY.LOW },
{ term: 'gadhi', severity: SEVERITY.LOW },
{ term: 'donkey', severity: SEVERITY.LOW },
{ term: 'idiot', severity: SEVERITY.LOW },
{ term: 'idiotic', severity: SEVERITY.LOW },
{ term: 'stupid', severity: SEVERITY.LOW },
{ term: 'stupid idiot', severity: SEVERITY.MEDIUM },
{ term: 'moron', severity: SEVERITY.MEDIUM },
{ term: 'moronic', severity: SEVERITY.MEDIUM },
{ term: 'dumbass', severity: SEVERITY.MEDIUM },
{ term: 'dumb idiot', severity: SEVERITY.MEDIUM },
{ term: 'dumbfuck', severity: SEVERITY.HIGH },
{ term: 'fuck', severity: SEVERITY.HIGH },
{ term: 'fucking', severity: SEVERITY.MEDIUM },
{ term: 'fucker', severity: SEVERITY.HIGH },
{ term: 'motherfucker', severity: SEVERITY.HIGH },
{ term: 'bullshit', severity: SEVERITY.MEDIUM },
{ term: 'shit', severity: SEVERITY.MEDIUM },
{ term: 'shithead', severity: SEVERITY.MEDIUM },
{ term: 'shitface', severity: SEVERITY.MEDIUM },
{ term: 'asshole', severity: SEVERITY.MEDIUM },
{ term: 'arsehole', severity: SEVERITY.MEDIUM },
{ term: 'ass', severity: SEVERITY.LOW },
{ term: 'asswipe', severity: SEVERITY.MEDIUM },
{ term: 'asshat', severity: SEVERITY.MEDIUM },
{ term: 'jackass', severity: SEVERITY.MEDIUM },
{ term: 'dick', severity: SEVERITY.MEDIUM },
{ term: 'dickhead', severity: SEVERITY.MEDIUM },
{ term: 'dickwad', severity: SEVERITY.MEDIUM },
{ term: 'douche', severity: SEVERITY.MEDIUM },
{ term: 'douchebag', severity: SEVERITY.MEDIUM },
{ term: 'bastard', severity: SEVERITY.MEDIUM },
{ term: 'son of a bitch', severity: SEVERITY.HIGH },
{ term: 'sob', severity: SEVERITY.MEDIUM },
{ term: 'prick', severity: SEVERITY.MEDIUM },
{ term: 'jerk', severity: SEVERITY.LOW },
{ term: 'jerkoff', severity: SEVERITY.MEDIUM },
{ term: 'wanker', severity: SEVERITY.MEDIUM },
{ term: 'twat', severity: SEVERITY.HIGH },
{ term: 'douchebag', severity: SEVERITY.MEDIUM },
{ term: 'scumbag', severity: SEVERITY.MEDIUM },
{ term: 'lowlife', severity: SEVERITY.MEDIUM },
{ term: 'piece of shit', severity: SEVERITY.HIGH },
{ term: 'piece of crap', severity: SEVERITY.MEDIUM },
{ term: 'son of a gun', severity: SEVERITY.LOW },
{ term: 'damn idiot', severity: SEVERITY.LOW },
{ term: 'damn fool', severity: SEVERITY.LOW },
{ term: 'fool', severity: SEVERITY.LOW },
{ term: 'foolish', severity: SEVERITY.LOW },
{ term: 'loser', severity: SEVERITY.LOW },
{ term: 'big loser', severity: SEVERITY.LOW },
{ term: 'pathetic loser', severity: SEVERITY.MEDIUM },
{ term: 'worthless', severity: SEVERITY.MEDIUM },
{ term: 'worthless idiot', severity: SEVERITY.MEDIUM },
{ term: 'useless', severity: SEVERITY.LOW },
{ term: 'useless idiot', severity: SEVERITY.MEDIUM },
{ term: 'clown', severity: SEVERITY.LOW },
{ term: 'stupid clown', severity: SEVERITY.MEDIUM },
{ term: 'fucking clown', severity: SEVERITY.HIGH },
{ term: 'creep', severity: SEVERITY.MEDIUM },
{ term: 'creepy bastard', severity: SEVERITY.MEDIUM },
{ term: 'pervert', severity: SEVERITY.HIGH },
{ term: 'perverted', severity: SEVERITY.MEDIUM },
{ term: 'creepy idiot', severity: SEVERITY.MEDIUM },
{ term: 'weirdo', severity: SEVERITY.LOW },
{ term: 'weird bastard', severity: SEVERITY.MEDIUM },
{ term: 'scammer', severity: SEVERITY.MEDIUM },
{ term: 'fraud', severity: SEVERITY.MEDIUM },
{ term: 'fraudster', severity: SEVERITY.MEDIUM },
{ term: 'cheater', severity: SEVERITY.LOW },
{ term: 'liar', severity: SEVERITY.LOW },
{ term: 'bloody liar', severity: SEVERITY.MEDIUM },
{ term: 'fake bastard', severity: SEVERITY.MEDIUM },
{ term: 'fake ass', severity: SEVERITY.MEDIUM },
{ term: 'attention seeker', severity: SEVERITY.LOW },
{ term: 'crybaby', severity: SEVERITY.LOW },
{ term: 'spoiled brat', severity: SEVERITY.LOW },
{ term: 'brat', severity: SEVERITY.LOW },
{ term: 'coward', severity: SEVERITY.LOW },
{ term: 'coward idiot', severity: SEVERITY.MEDIUM },
{ term: 'hypocrite', severity: SEVERITY.LOW },
{ term: 'hypocritical bastard', severity: SEVERITY.MEDIUM },
{ term: 'liar bastard', severity: SEVERITY.MEDIUM },
{ term: 'dirty liar', severity: SEVERITY.MEDIUM },
{ term: 'dirty bastard', severity: SEVERITY.MEDIUM },
{ term: 'dirty dog', severity: SEVERITY.MEDIUM },
{ term: 'dirty pig', severity: SEVERITY.MEDIUM },
{ term: 'filthy pig', severity: SEVERITY.MEDIUM },
{ term: 'filthy bastard', severity: SEVERITY.MEDIUM },
{ term: 'filthy idiot', severity: SEVERITY.MEDIUM },
{ term: 'disgusting', severity: SEVERITY.LOW },
{ term: 'disgusting bastard', severity: SEVERITY.MEDIUM },
{ term: 'disgusting pig', severity: SEVERITY.MEDIUM },
{ term: 'sick bastard', severity: SEVERITY.MEDIUM },
{ term: 'sicko', severity: SEVERITY.MEDIUM },
{ term: 'psycho', severity: SEVERITY.MEDIUM },
{ term: 'freak', severity: SEVERITY.LOW },
{ term: 'stupid freak', severity: SEVERITY.MEDIUM },
{ term: 'creepy freak', severity: SEVERITY.MEDIUM },
{ term: 'trash', severity: SEVERITY.MEDIUM },
{ term: 'human trash', severity: SEVERITY.MEDIUM },
{ term: 'garbage', severity: SEVERITY.LOW },
{ term: 'piece of garbage', severity: SEVERITY.MEDIUM },
{ term: 'scum', severity: SEVERITY.MEDIUM },
{ term: 'human scum', severity: SEVERITY.HIGH },
{ term: 'vermin', severity: SEVERITY.MEDIUM },
{ term: 'parasite', severity: SEVERITY.MEDIUM },
{ term: 'leech', severity: SEVERITY.LOW },
{ term: 'rat', severity: SEVERITY.LOW },
{ term: 'dirty rat', severity: SEVERITY.MEDIUM },
{ term: 'snake', severity: SEVERITY.LOW },
{ term: 'two faced', severity: SEVERITY.LOW },
{ term: 'two faced bastard', severity: SEVERITY.MEDIUM },
{ term: 'fake friend', severity: SEVERITY.LOW },
{ term: 'backstabber', severity: SEVERITY.MEDIUM },
{ term: 'traitor', severity: SEVERITY.MEDIUM },
{ term: 'cheater bastard', severity: SEVERITY.MEDIUM },
{ term: 'attention whore', severity: SEVERITY.HIGH },
{ term: 'drama queen', severity: SEVERITY.LOW },
{ term: 'crying bitch', severity: SEVERITY.HIGH },
{ term: 'bitch', severity: SEVERITY.MEDIUM },
{ term: 'bitchy', severity: SEVERITY.MEDIUM },
{ term: 'son of a bitch', severity: SEVERITY.HIGH },
{ term: 'bitch ass', severity: SEVERITY.HIGH },
{ term: 'bitch boy', severity: SEVERITY.HIGH },
{ term: 'bitch girl', severity: SEVERITY.MEDIUM },
{ term: 'dumb bitch', severity: SEVERITY.HIGH },
{ term: 'stupid bitch', severity: SEVERITY.HIGH },
{ term: 'crazy bitch', severity: SEVERITY.HIGH },
{ term: 'dirty bitch', severity: SEVERITY.HIGH },
{ term: 'selfish bitch', severity: SEVERITY.MEDIUM },
{ term: 'bloody bastard', severity: SEVERITY.MEDIUM },
{ term: 'bloody asshole', severity: SEVERITY.MEDIUM },
{ term: 'fucking asshole', severity: SEVERITY.HIGH },
{ term: 'fucking idiot', severity: SEVERITY.HIGH },
{ term: 'fucking moron', severity: SEVERITY.HIGH },
{ term: 'fucking loser', severity: SEVERITY.HIGH },
{ term: 'fucking liar', severity: SEVERITY.HIGH },
{ term: 'fucking prick', severity: SEVERITY.HIGH },
{ term: 'fuck off', severity: SEVERITY.HIGH },
{ term: 'fuck you', severity: SEVERITY.HIGH },
{ term: 'fuck this', severity: SEVERITY.MEDIUM },
{ term: 'fuck that', severity: SEVERITY.MEDIUM },
{ term: 'go fuck yourself', severity: SEVERITY.HIGH },
{ term: 'shut the fuck up', severity: SEVERITY.HIGH },
{ term: 'get the fuck out', severity: SEVERITY.HIGH },
{ term: 'what the fuck', severity: SEVERITY.MEDIUM },
{ term: 'who the fuck', severity: SEVERITY.MEDIUM },
{ term: 'bloody fool', severity: SEVERITY.LOW },
{ term: 'bloody idiot', severity: SEVERITY.MEDIUM },
{ term: 'bloody moron', severity: SEVERITY.MEDIUM },
{ term: 'screw you', severity: SEVERITY.MEDIUM },
{ term: 'screw off', severity: SEVERITY.MEDIUM },
{ term: 'piss off', severity: SEVERITY.MEDIUM },
{ term: 'pissed idiot', severity: SEVERITY.MEDIUM },
{ term: 'kiss my ass', severity: SEVERITY.MEDIUM },
{ term: 'up yours', severity: SEVERITY.MEDIUM },
{ term: 'get lost idiot', severity: SEVERITY.LOW },
{ term: 'get lost loser', severity: SEVERITY.LOW },
{ term: 'shut up idiot', severity: SEVERITY.MEDIUM },
{ term: 'shut up moron', severity: SEVERITY.MEDIUM },
{ term: 'shut your mouth', severity: SEVERITY.LOW },
{ term: 'keep your mouth shut', severity: SEVERITY.LOW },
{ term: 'mind your own business idiot', severity: SEVERITY.LOW },
{ term: 'teri maa ki', severity: SEVERITY.HIGH },
{ term: 'teri behen ki', severity: SEVERITY.HIGH },
{ term: 'maa ki chut', severity: SEVERITY.HIGH },
{ term: 'maa chuda', severity: SEVERITY.HIGH },
{ term: 'maa chudao', severity: SEVERITY.HIGH },
{ term: 'maa chudane ja', severity: SEVERITY.HIGH },
{ term: 'behen ki chut', severity: SEVERITY.HIGH },
{ term: 'behen chuda', severity: SEVERITY.HIGH },
{ term: 'behen chudao', severity: SEVERITY.HIGH },
{ term: 'baap ka naukar', severity: SEVERITY.MEDIUM },
{ term: 'baap ka paisa', severity: SEVERITY.LOW },
{ term: 'baap se puch', severity: SEVERITY.LOW },
{ term: 'teri maa', severity: SEVERITY.MEDIUM },
{ term: 'teri behen', severity: SEVERITY.MEDIUM },
{ term: 'teri aukaat nahi', severity: SEVERITY.MEDIUM },
{ term: 'aukaat nahi hai', severity: SEVERITY.MEDIUM },
{ term: 'apni aukaat dekh', severity: SEVERITY.MEDIUM },
{ term: 'apni shakal dekh', severity: SEVERITY.LOW },
{ term: 'shakal se hi chutiya', severity: SEVERITY.MEDIUM },
{ term: 'dimaag ghutne mein hai', severity: SEVERITY.MEDIUM },
{ term: 'dimaag bech ke aaya', severity: SEVERITY.MEDIUM },
{ term: 'akal bech di kya', severity: SEVERITY.MEDIUM },
{ term: 'dimag nahi hai kya', severity: SEVERITY.LOW },
{ term: 'kya chutiya hai', severity: SEVERITY.MEDIUM },
{ term: 'kitna chutiya hai', severity: SEVERITY.MEDIUM },
{ term: 'chutiya insaan', severity: SEVERITY.MEDIUM },
{ term: 'chutiya aadmi', severity: SEVERITY.MEDIUM },
{ term: 'chutiya banda', severity: SEVERITY.MEDIUM },
{ term: 'chutiya bandi', severity: SEVERITY.MEDIUM },
{ term: 'chutiya ladka', severity: SEVERITY.MEDIUM },
{ term: 'chutiya ladki', severity: SEVERITY.MEDIUM },
{ term: 'harami banda', severity: SEVERITY.MEDIUM },
{ term: 'harami bandi', severity: SEVERITY.MEDIUM },
{ term: 'kamina banda', severity: SEVERITY.MEDIUM },
{ term: 'kamini bandi', severity: SEVERITY.MEDIUM },
{ term: 'nalayak banda', severity: SEVERITY.LOW },
{ term: 'nalayak bandi', severity: SEVERITY.LOW },
{ term: 'bakchod banda', severity: SEVERITY.MEDIUM },
{ term: 'bakchod bandi', severity: SEVERITY.MEDIUM },
{ term: 'jhantu banda', severity: SEVERITY.MEDIUM },
{ term: 'jhantu aadmi', severity: SEVERITY.MEDIUM },
{ term: 'jhantu insaan', severity: SEVERITY.MEDIUM },
{ term: 'faltu banda', severity: SEVERITY.LOW },
{ term: 'faltu bandi', severity: SEVERITY.LOW },
{ term: 'nikamma banda', severity: SEVERITY.LOW },
{ term: 'nikammi bandi', severity: SEVERITY.LOW },
{ term: 'mawaali', severity: SEVERITY.MEDIUM },
{ term: 'mawali', severity: SEVERITY.MEDIUM },
{ term: 'tapori', severity: SEVERITY.LOW },
{ term: 'lafda', severity: SEVERITY.LOW },
{ term: 'lafdebaaz', severity: SEVERITY.MEDIUM },
{ term: 'lafanga', severity: SEVERITY.MEDIUM },
{ term: 'chhapri', severity: SEVERITY.MEDIUM },
{ term: 'chapri', severity: SEVERITY.MEDIUM },
{ term: 'chapri saala', severity: SEVERITY.MEDIUM },
{ term: 'chhapri saala', severity: SEVERITY.MEDIUM },
{ term: 'nalla', severity: SEVERITY.LOW },
{ term: 'nalle', severity: SEVERITY.LOW },
{ term: 'nalla aadmi', severity: SEVERITY.LOW },
{ term: 'nalla banda', severity: SEVERITY.LOW },
{ term: 'jhalla', severity: SEVERITY.LOW },
{ term: 'pagal kutta', severity: SEVERITY.MEDIUM },
{ term: 'pagal saala', severity: SEVERITY.MEDIUM },
{ term: 'pagal aadmi', severity: SEVERITY.LOW },
{ term: 'pagal aurat', severity: SEVERITY.LOW },
{ term: 'sarphira', severity: SEVERITY.MEDIUM },
{ term: 'sarphira aadmi', severity: SEVERITY.MEDIUM },
{ term: 'dimaag kharab hai', severity: SEVERITY.LOW },
{ term: 'dimaag ka dahi', severity: SEVERITY.LOW },
{ term: 'bakwaas insaan', severity: SEVERITY.LOW },
{ term: 'bakwaas banda', severity: SEVERITY.LOW },
{ term: 'bakwaas bandi', severity: SEVERITY.LOW },
{ term: 'ghatiya banda', severity: SEVERITY.MEDIUM },
{ term: 'ghatiya bandi', severity: SEVERITY.MEDIUM },
{ term: 'ghatiya soch', severity: SEVERITY.LOW },
{ term: 'gandi soch wala', severity: SEVERITY.MEDIUM },
{ term: 'gandi soch wali', severity: SEVERITY.MEDIUM },
{ term: 'doob mar', severity: SEVERITY.MEDIUM },
{ term: 'sharam kar', severity: SEVERITY.LOW },
{ term: 'sharam nahi aati', severity: SEVERITY.LOW },
{ term: 'sharam se doob mar', severity: SEVERITY.MEDIUM },
{ term: 'nikamma kahin ka', severity: SEVERITY.LOW },
{ term: 'nalayak kahin ka', severity: SEVERITY.LOW },
{ term: 'haramkhor kahin ka', severity: SEVERITY.HIGH },
{ term: 'harami kahin ka', severity: SEVERITY.MEDIUM },
{ term: 'kamina kahin ka', severity: SEVERITY.MEDIUM },
{ term: 'chutiya kahin ka', severity: SEVERITY.MEDIUM },
{ term: 'gandu kahin ka', severity: SEVERITY.MEDIUM },
{ term: 'saala kutta', severity: SEVERITY.MEDIUM },
{ term: 'saala harami', severity: SEVERITY.MEDIUM },
{ term: 'saala kamina', severity: SEVERITY.MEDIUM },
{ term: 'saala chutiya', severity: SEVERITY.MEDIUM },
{ term: 'saala gandu', severity: SEVERITY.MEDIUM },
{ term: 'saala bakchod', severity: SEVERITY.MEDIUM },

// Marathi
{ term: 'bhadva', severity: SEVERITY.HIGH },
{ term: 'bhadwe', severity: SEVERITY.HIGH },
{ term: 'bhadva saala', severity: SEVERITY.HIGH },
{ term: 'bhadwya', severity: SEVERITY.HIGH },
{ term: 'zavnya', severity: SEVERITY.HIGH },
{ term: 'zhavnya', severity: SEVERITY.HIGH },
{ term: 'zavada', severity: SEVERITY.HIGH },
{ term: 'zhavada', severity: SEVERITY.HIGH },
{ term: 'zavli', severity: SEVERITY.HIGH },
{ term: 'zhavli', severity: SEVERITY.HIGH },
{ term: 'aichya gavat', severity: SEVERITY.HIGH },
{ term: 'aai zhavadli', severity: SEVERITY.HIGH },
{ term: 'aai zavli', severity: SEVERITY.HIGH },
{ term: 'aai ghalya', severity: SEVERITY.HIGH },
{ term: 'aai ghalya', severity: SEVERITY.HIGH },
{ term: 'bokkya', severity: SEVERITY.MEDIUM },
{ term: 'bhikarchot', severity: SEVERITY.MEDIUM },
{ term: 'bhikarchot saala', severity: SEVERITY.MEDIUM },
{ term: 'bhikarchotya', severity: SEVERITY.MEDIUM },
{ term: 'yeda', severity: SEVERITY.LOW },
{ term: 'yedyachap', severity: SEVERITY.MEDIUM },
{ term: 'yedyagabal', severity: SEVERITY.MEDIUM },
{ term: 'vedpat', severity: SEVERITY.MEDIUM },
{ term: 'vedya', severity: SEVERITY.LOW },
{ term: 'gadhav', severity: SEVERITY.LOW },
{ term: 'gadhava', severity: SEVERITY.LOW },
{ term: 'haramkhor', severity: SEVERITY.HIGH },
{ term: 'nalayak manus', severity: SEVERITY.LOW },
{ term: 'ghati manus', severity: SEVERITY.MEDIUM },
{ term: 'ghatiya manus', severity: SEVERITY.MEDIUM },
{ term: 'kamina manus', severity: SEVERITY.MEDIUM },
{ term: 'harami manus', severity: SEVERITY.MEDIUM },
{ term: 'chapri', severity: SEVERITY.MEDIUM },
{ term: 'tapori', severity: SEVERITY.LOW },
{ term: 'mawali', severity: SEVERITY.MEDIUM },
{ term: 'mawali saala', severity: SEVERITY.MEDIUM },
{ term: 'aai zhavadya', severity: SEVERITY.HIGH },
{ term: 'aai zavdya', severity: SEVERITY.HIGH },
{ term: 'zavdya', severity: SEVERITY.HIGH },
{ term: 'zhavdya', severity: SEVERITY.HIGH },
{ term: 'zavayla', severity: SEVERITY.HIGH },
{ term: 'zhavayla', severity: SEVERITY.HIGH },
{ term: 'zavun ghe', severity: SEVERITY.HIGH },
{ term: 'zhavun ghe', severity: SEVERITY.HIGH },
{ term: 'bhikarchot saala', severity: SEVERITY.MEDIUM },
{ term: 'yeda sala', severity: SEVERITY.MEDIUM },
{ term: 'gadhav saala', severity: SEVERITY.MEDIUM },
{ term: 'haramkhor saala', severity: SEVERITY.HIGH },
{ term: 'bhadwya saala', severity: SEVERITY.HIGH },
{ term: 'nalayak saala', severity: SEVERITY.MEDIUM },
{ term: 'ghatiya saala', severity: SEVERITY.MEDIUM },
{ term: 'aai chi ghaan', severity: SEVERITY.HIGH },
{ term: 'baapacha naukar', severity: SEVERITY.LOW },
{ term: 'kay re yedya', severity: SEVERITY.LOW },
{ term: 'kay re gadhava', severity: SEVERITY.LOW },
{ term: 'chup re yedya', severity: SEVERITY.LOW },
{ term: 'chup re gadhava', severity: SEVERITY.LOW },
{ term: 'bewaqoof insaan', severity: SEVERITY.LOW },
{ term: 'bewaqoof aadmi', severity: SEVERITY.LOW },
{ term: 'bewaqoof banda', severity: SEVERITY.LOW },
{ term: 'bevakoof insaan', severity: SEVERITY.LOW },
{ term: 'bevakoof aadmi', severity: SEVERITY.LOW },
{ term: 'bevakoof banda', severity: SEVERITY.LOW },
{ term: 'maha bewakoof', severity: SEVERITY.MEDIUM },
{ term: 'poora bewakoof', severity: SEVERITY.LOW },
{ term: 'bahut bada bewakoof', severity: SEVERITY.MEDIUM },
{ term: 'akal ka dushman', severity: SEVERITY.LOW },
{ term: 'akal ka andha', severity: SEVERITY.MEDIUM },
{ term: 'akal nahi hai', severity: SEVERITY.LOW },
{ term: 'akal ghaas charne gayi', severity: SEVERITY.LOW },
{ term: 'dimaag ghar pe chhod aaya', severity: SEVERITY.LOW },
{ term: 'dimaag ghar pe chhod aayi', severity: SEVERITY.LOW },
{ term: 'dimaag kaam nahi karta', severity: SEVERITY.LOW },
{ term: 'dimaag zero hai', severity: SEVERITY.LOW },
{ term: 'dimaag kharab aadmi', severity: SEVERITY.MEDIUM },
{ term: 'dimaag kharab banda', severity: SEVERITY.MEDIUM },
{ term: 'dimaag kharab insaan', severity: SEVERITY.MEDIUM },
{ term: 'dimaghi', severity: SEVERITY.LOW },
{ term: 'sarphira', severity: SEVERITY.MEDIUM },
{ term: 'sanaki', severity: SEVERITY.LOW },
{ term: 'sanak gaya', severity: SEVERITY.LOW },
{ term: 'sanak gayi', severity: SEVERITY.LOW },
{ term: 'pagalpan', severity: SEVERITY.LOW },
{ term: 'pagalpanti', severity: SEVERITY.LOW },
{ term: 'pagalpanti kar', severity: SEVERITY.LOW },
{ term: 'mental case', severity: SEVERITY.MEDIUM },
{ term: 'mental piece', severity: SEVERITY.MEDIUM },
{ term: 'dimaghi case', severity: SEVERITY.MEDIUM },
{ term: 'naadan', severity: SEVERITY.LOW },
{ term: 'anpadh', severity: SEVERITY.LOW },
{ term: 'anpadh gawar', severity: SEVERITY.MEDIUM },
{ term: 'gawar', severity: SEVERITY.MEDIUM },
{ term: 'gawaar', severity: SEVERITY.MEDIUM },
{ term: 'gawar aadmi', severity: SEVERITY.MEDIUM },
{ term: 'gawar banda', severity: SEVERITY.MEDIUM },
{ term: 'gawar insaan', severity: SEVERITY.MEDIUM },
{ term: 'jungli', severity: SEVERITY.LOW },
{ term: 'jungli aadmi', severity: SEVERITY.MEDIUM },
{ term: 'jungli banda', severity: SEVERITY.MEDIUM },
{ term: 'buddhu', severity: SEVERITY.LOW },
{ term: 'buddhu aadmi', severity: SEVERITY.LOW },
{ term: 'buddhu banda', severity: SEVERITY.LOW },
{ term: 'dhakkan', severity: SEVERITY.LOW },
{ term: 'dhakkan aadmi', severity: SEVERITY.MEDIUM },
{ term: 'dhakkan banda', severity: SEVERITY.MEDIUM },
{ term: 'dhakkan insaan', severity: SEVERITY.MEDIUM },
{ term: 'dheela dimaag', severity: SEVERITY.LOW },
{ term: 'dheela aadmi', severity: SEVERITY.LOW },
{ term: 'khopdi khaali', severity: SEVERITY.LOW },
{ term: 'khopdi mein kuch nahi', severity: SEVERITY.LOW },
{ term: 'khopdi kharab', severity: SEVERITY.LOW },
{ term: 'dimag kharab banda', severity: SEVERITY.LOW },
{ term: 'ulta dimaag', severity: SEVERITY.LOW },
{ term: 'tedha dimaag', severity: SEVERITY.LOW },
{ term: 'khurafati dimaag', severity: SEVERITY.LOW },
{ term: 'khurafati', severity: SEVERITY.LOW },
{ term: 'dramebaaz', severity: SEVERITY.LOW },
{ term: 'dramebaaz aadmi', severity: SEVERITY.LOW },
{ term: 'dramebaaz banda', severity: SEVERITY.LOW },
{ term: 'nautanki', severity: SEVERITY.LOW },
{ term: 'nautanki baaz', severity: SEVERITY.LOW },
{ term: 'nautanki aadmi', severity: SEVERITY.LOW },
{ term: 'nautanki banda', severity: SEVERITY.LOW },
{ term: 'tamasha mat kar', severity: SEVERITY.LOW },
{ term: 'drama band kar', severity: SEVERITY.LOW },
{ term: 'natak band kar', severity: SEVERITY.LOW },
{ term: 'natakbaaz', severity: SEVERITY.LOW },
{ term: 'jhootha', severity: SEVERITY.LOW },
{ term: 'jhoothi', severity: SEVERITY.LOW },
{ term: 'jhootha aadmi', severity: SEVERITY.MEDIUM },
{ term: 'jhoothi aurat', severity: SEVERITY.MEDIUM },
{ term: 'jhootha banda', severity: SEVERITY.LOW },
{ term: 'jhoothi bandi', severity: SEVERITY.LOW },
{ term: 'pakka jhootha', severity: SEVERITY.MEDIUM },
{ term: 'number one liar', severity: SEVERITY.MEDIUM },
{ term: 'dhokebaaz', severity: SEVERITY.MEDIUM },
{ term: 'dhokebaaz aadmi', severity: SEVERITY.MEDIUM },
{ term: 'dhokebaaz banda', severity: SEVERITY.MEDIUM },
{ term: 'dhokhebaaz', severity: SEVERITY.MEDIUM },
{ term: 'farebi', severity: SEVERITY.MEDIUM },
{ term: 'farebi insaan', severity: SEVERITY.MEDIUM },
{ term: 'makkaar', severity: SEVERITY.MEDIUM },
{ term: 'makkaar aadmi', severity: SEVERITY.MEDIUM },
{ term: 'makkaar banda', severity: SEVERITY.MEDIUM },
{ term: 'matlabi', severity: SEVERITY.LOW },
{ term: 'matlabi insaan', severity: SEVERITY.LOW },
{ term: 'matlabi banda', severity: SEVERITY.LOW },
{ term: 'swarthi', severity: SEVERITY.LOW },
{ term: 'lalchi', severity: SEVERITY.LOW },
{ term: 'lalchi aadmi', severity: SEVERITY.LOW },
{ term: 'lalchi banda', severity: SEVERITY.LOW },
{ term: 'chor', severity: SEVERITY.MEDIUM },
{ term: 'chor saala', severity: SEVERITY.MEDIUM },
{ term: 'chor aadmi', severity: SEVERITY.MEDIUM },
{ term: 'chor banda', severity: SEVERITY.MEDIUM },
{ term: 'chori karne wala', severity: SEVERITY.MEDIUM },
{ term: 'fraudiya', severity: SEVERITY.MEDIUM },
{ term: 'fraudbaaz', severity: SEVERITY.MEDIUM },
{ term: 'dhokhebaaz saala', severity: SEVERITY.MEDIUM },
{ term: 'pakhandi', severity: SEVERITY.MEDIUM },
{ term: 'pakhandi aadmi', severity: SEVERITY.MEDIUM },
{ term: 'pakhandi banda', severity: SEVERITY.MEDIUM },
{ term: 'do numberi', severity: SEVERITY.MEDIUM },
{ term: 'do number ka aadmi', severity: SEVERITY.MEDIUM },
{ term: 'do number ka banda', severity: SEVERITY.MEDIUM },
{ term: 'lafda karne wala', severity: SEVERITY.LOW },
{ term: 'lafdebaaz', severity: SEVERITY.MEDIUM },
{ term: 'panga lene wala', severity: SEVERITY.LOW },
{ term: 'pangebaaz', severity: SEVERITY.LOW },
{ term: 'jhagdaalu', severity: SEVERITY.LOW },
{ term: 'jhagdaalu aadmi', severity: SEVERITY.LOW },
{ term: 'jhagdaalu banda', severity: SEVERITY.LOW },
{ term: 'ladaku', severity: SEVERITY.LOW },
{ term: 'ladaku aadmi', severity: SEVERITY.LOW },
{ term: 'ladaku banda', severity: SEVERITY.LOW },
{ term: 'gunda', severity: SEVERITY.MEDIUM },
{ term: 'gunde', severity: SEVERITY.MEDIUM },
{ term: 'gundagardi', severity: SEVERITY.MEDIUM },
{ term: 'gunda aadmi', severity: SEVERITY.MEDIUM },
{ term: 'gunda banda', severity: SEVERITY.MEDIUM },
{ term: 'badmaash', severity: SEVERITY.MEDIUM },
{ term: 'badmaash aadmi', severity: SEVERITY.MEDIUM },
{ term: 'badmaash banda', severity: SEVERITY.MEDIUM },
{ term: 'badmaashi', severity: SEVERITY.LOW },
{ term: 'uchakka', severity: SEVERITY.MEDIUM },
{ term: 'uchakke', severity: SEVERITY.MEDIUM },
{ term: 'awara ladka', severity: SEVERITY.LOW },
{ term: 'awara ladki', severity: SEVERITY.LOW },
{ term: 'besharam banda', severity: SEVERITY.MEDIUM },
{ term: 'besharam bandi', severity: SEVERITY.MEDIUM },
{ term: 'sharmnaak', severity: SEVERITY.LOW },
{ term: 'sharamheen', severity: SEVERITY.MEDIUM },
{ term: 'nirdayi', severity: SEVERITY.MEDIUM },
{ term: 'ziddi', severity: SEVERITY.LOW },
{ term: 'ziddi insaan', severity: SEVERITY.LOW },
{ term: 'akadbaaz', severity: SEVERITY.MEDIUM },
{ term: 'akaddu', severity: SEVERITY.LOW },
{ term: 'akaddu aadmi', severity: SEVERITY.LOW },
{ term: 'ghamandi', severity: SEVERITY.MEDIUM },
{ term: 'ghamandi aadmi', severity: SEVERITY.MEDIUM },
{ term: 'ghamandi banda', severity: SEVERITY.MEDIUM },
{ term: 'ahankaari', severity: SEVERITY.LOW },
{ term: 'egoistic idiot', severity: SEVERITY.MEDIUM },
{ term: 'egoistic bastard', severity: SEVERITY.MEDIUM },
{ term: 'overacting kar raha', severity: SEVERITY.LOW },
{ term: 'overacting kar rahi', severity: SEVERITY.LOW },
{ term: 'fake aadmi', severity: SEVERITY.LOW },
{ term: 'fake banda', severity: SEVERITY.LOW },
{ term: 'fake insaan', severity: SEVERITY.LOW },
{ term: 'nakli aadmi', severity: SEVERITY.LOW },
{ term: 'nakli banda', severity: SEVERITY.LOW },
{ term: 'nakli insaan', severity: SEVERITY.LOW },
{ term: 'dhongi', severity: SEVERITY.MEDIUM },
{ term: 'dhongi aadmi', severity: SEVERITY.MEDIUM },
{ term: 'dhongi banda', severity: SEVERITY.MEDIUM },
{ term: 'chalu aadmi', severity: SEVERITY.LOW },
{ term: 'chalu banda', severity: SEVERITY.LOW },
{ term: 'chalak lomdi', severity: SEVERITY.LOW },
{ term: 'lomdi', severity: SEVERITY.LOW },
{ term: 'saanp', severity: SEVERITY.LOW },
{ term: 'zehreela insaan', severity: SEVERITY.MEDIUM },
{ term: 'toxic aadmi', severity: SEVERITY.MEDIUM },
{ term: 'toxic banda', severity: SEVERITY.MEDIUM },
{ term: 'toxic person', severity: SEVERITY.MEDIUM },
{ term: 'annoying idiot', severity: SEVERITY.MEDIUM },
{ term: 'annoying bastard', severity: SEVERITY.MEDIUM },
{ term: 'irritating idiot', severity: SEVERITY.MEDIUM },
{ term: 'irritating bastard', severity: SEVERITY.MEDIUM },
{ term: 'pain in the ass', severity: SEVERITY.MEDIUM },
{ term: 'pain in my ass', severity: SEVERITY.MEDIUM },
{ term: 'shut your damn mouth', severity: SEVERITY.MEDIUM },
{ term: 'damn you', severity: SEVERITY.MEDIUM },
{ term: 'damn bastard', severity: SEVERITY.MEDIUM },
{ term: 'damn asshole', severity: SEVERITY.MEDIUM },
{ term: 'damn fool', severity: SEVERITY.LOW },
{ term: 'bloody asshole', severity: SEVERITY.MEDIUM },
{ term: 'bloody bastard', severity: SEVERITY.MEDIUM },
{ term: 'bloody fool', severity: SEVERITY.LOW },
{ term: 'bloody moron', severity: SEVERITY.MEDIUM },
{ term: 'bloody idiot', severity: SEVERITY.MEDIUM },
{ term: 'what a loser', severity: SEVERITY.LOW },
{ term: 'what an idiot', severity: SEVERITY.LOW },
{ term: 'what a moron', severity: SEVERITY.MEDIUM },
{ term: 'what a bastard', severity: SEVERITY.MEDIUM },
{ term: 'you loser', severity: SEVERITY.LOW },
{ term: 'you moron', severity: SEVERITY.MEDIUM },
{ term: 'you idiot', severity: SEVERITY.LOW },
{ term: 'you asshole', severity: SEVERITY.MEDIUM },
{ term: 'you bastard', severity: SEVERITY.MEDIUM },
{ term: 'go away idiot', severity: SEVERITY.LOW },
{ term: 'go away loser', severity: SEVERITY.LOW },
{ term: 'get out loser', severity: SEVERITY.LOW },
{ term: 'get out idiot', severity: SEVERITY.LOW },
{ term: 'shut it', severity: SEVERITY.LOW },
{ term: 'shut up fool', severity: SEVERITY.LOW },
{ term: 'shut up clown', severity: SEVERITY.LOW },
{ term: 'stop whining', severity: SEVERITY.LOW },
{ term: 'stop crying', severity: SEVERITY.LOW },
{ term: 'stop your drama', severity: SEVERITY.LOW },
{ term: 'cry somewhere else', severity: SEVERITY.LOW },
{ term: 'nobody likes you', severity: SEVERITY.MEDIUM },
{ term: 'nobody wants you', severity: SEVERITY.MEDIUM },
{ term: 'you are useless', severity: SEVERITY.MEDIUM },
{ term: 'you are pathetic', severity: SEVERITY.MEDIUM },
{ term: 'you are disgusting', severity: SEVERITY.MEDIUM },
{ term: 'you are annoying', severity: SEVERITY.LOW },
{ term: 'you are a clown', severity: SEVERITY.LOW },
{ term: 'you are a loser', severity: SEVERITY.LOW },
{ term: 'you are a moron', severity: SEVERITY.MEDIUM },
{ term: 'you are an idiot', severity: SEVERITY.LOW },
{ term: 'you are an asshole', severity: SEVERITY.MEDIUM },
{ term: 'you are a bastard', severity: SEVERITY.MEDIUM },
{ term: 'teri soch ghatiya hai', severity: SEVERITY.MEDIUM },
{ term: 'teri soch gandi hai', severity: SEVERITY.MEDIUM },
{ term: 'soch badal le', severity: SEVERITY.LOW },
{ term: 'shakal dekh pehle', severity: SEVERITY.LOW },
{ term: 'shakal se hi bewakoof', severity: SEVERITY.MEDIUM },
{ term: 'shakal se hi gadha', severity: SEVERITY.MEDIUM },
{ term: 'dekh ke hi pata chal raha', severity: SEVERITY.LOW },
{ term: 'kya bakwaas aadmi hai', severity: SEVERITY.MEDIUM },
{ term: 'kya bakwaas banda hai', severity: SEVERITY.MEDIUM },
{ term: 'kya ghatiya aadmi hai', severity: SEVERITY.MEDIUM },
{ term: 'kya ghatiya banda hai', severity: SEVERITY.MEDIUM },
{ term: 'kya nalayak aadmi hai', severity: SEVERITY.LOW },
{ term: 'kya nalayak banda hai', severity: SEVERITY.LOW },
{ term: 'kya harami hai', severity: SEVERITY.MEDIUM },
{ term: 'kya kamina hai', severity: SEVERITY.MEDIUM },
{ term: 'kya bakchod hai', severity: SEVERITY.MEDIUM },
{ term: 'kya nautanki hai', severity: SEVERITY.LOW },
{ term: 'kya dramebaaz hai', severity: SEVERITY.LOW },
{ term: 'kya chhapri hai', severity: SEVERITY.MEDIUM },
{ term: 'chhapri behaviour', severity: SEVERITY.MEDIUM },
{ term: 'chapri behaviour', severity: SEVERITY.MEDIUM },
{ term: 'chapri banda', severity: SEVERITY.MEDIUM },
{ term: 'chapri ladka', severity: SEVERITY.MEDIUM },
{ term: 'chapri ladki', severity: SEVERITY.MEDIUM },
{ term: 'chapri mentality', severity: SEVERITY.MEDIUM },
{ term: 'chapri mindset', severity: SEVERITY.MEDIUM },
{ term: 'nalla behaviour', severity: SEVERITY.LOW },
{ term: 'nalla banda', severity: SEVERITY.LOW },
{ term: 'nalla insaan', severity: SEVERITY.LOW },
{ term: 'kaamchor', severity: SEVERITY.LOW },
{ term: 'kaamchor aadmi', severity: SEVERITY.LOW },
{ term: 'kaamchor banda', severity: SEVERITY.LOW },
{ term: 'nikamma', severity: SEVERITY.LOW },
{ term: 'nikamma aadmi', severity: SEVERITY.LOW },
{ term: 'nikamma banda', severity: SEVERITY.LOW },
{ term: 'nikammi aadmi', severity: SEVERITY.LOW },
{ term: 'nikammi bandi', severity: SEVERITY.LOW },
{ term: 'sust aadmi', severity: SEVERITY.LOW },
{ term: 'sust banda', severity: SEVERITY.LOW },
{ term: 'aalsi aadmi', severity: SEVERITY.LOW },
{ term: 'aalsi banda', severity: SEVERITY.LOW },
{ term: 'kaam ka nahi', severity: SEVERITY.LOW },
{ term: 'kisi kaam ka nahi', severity: SEVERITY.MEDIUM },
{ term: 'kisi kaam ka nahi hai', severity: SEVERITY.MEDIUM },
{ term: 'bekaar aadmi', severity: SEVERITY.LOW },
{ term: 'bekaar banda', severity: SEVERITY.LOW },
{ term: 'bekaar insaan', severity: SEVERITY.LOW },
{ term: 'bekaar dimaag', severity: SEVERITY.LOW },
{ term: 'faltu insaan', severity: SEVERITY.LOW },
{ term: 'faltu banda', severity: SEVERITY.LOW },
{ term: 'faltu aadmi', severity: SEVERITY.LOW },
{ term: 'nikal yahan se saale', severity: SEVERITY.MEDIUM },
{ term: 'nikal yahan se kamine', severity: SEVERITY.MEDIUM },
{ term: 'nikal yahan se harami', severity: SEVERITY.MEDIUM },
{ term: 'bhaag yahan se saale', severity: SEVERITY.MEDIUM },
{ term: 'bhaag yahan se kamine', severity: SEVERITY.MEDIUM },
{ term: 'dafa ho saale', severity: SEVERITY.MEDIUM },
{ term: 'dafa ho kamine', severity: SEVERITY.MEDIUM },
{ term: 'chup ho ja saale', severity: SEVERITY.MEDIUM },
{ term: 'chup ho ja kamine', severity: SEVERITY.MEDIUM },
{ term: 'munh band rakh', severity: SEVERITY.LOW },
{ term: 'apna munh band rakh', severity: SEVERITY.LOW },
{ term: 'bakwaas mat kar', severity: SEVERITY.LOW },
{ term: 'bakwaas karna band kar', severity: SEVERITY.LOW },
{ term: 'drama mat kar', severity: SEVERITY.LOW },
{ term: 'nautanki mat kar', severity: SEVERITY.LOW },
{ term: 'overacting band kar', severity: SEVERITY.LOW },
{ term: 'apni bakwaas band kar', severity: SEVERITY.MEDIUM },
{ term: 'apni nautanki band kar', severity: SEVERITY.LOW },
{ term: 'apna drama band kar', severity: SEVERITY.LOW },
{ term: 'chup chap nikal', severity: SEVERITY.LOW },
{ term: 'chup chap ja', severity: SEVERITY.LOW },
{ term: 'yahan se nikal', severity: SEVERITY.LOW },
{ term: 'door ho ja', severity: SEVERITY.LOW },
{ term: 'mere saamne mat aa', severity: SEVERITY.LOW },
{ term: 'shakal mat dikha', severity: SEVERITY.LOW },
{ term: 'dobara mat dikhna', severity: SEVERITY.MEDIUM },
{ term: 'dikh mat jana', severity: SEVERITY.LOW },
{ term: 'nikal ja yahan se', severity: SEVERITY.LOW },
{ term: 'chal hatt', severity: SEVERITY.LOW },
{ term: 'hatt saale', severity: SEVERITY.MEDIUM },
{ term: 'hatt kamine', severity: SEVERITY.MEDIUM },
{ term: 'hatt harami', severity: SEVERITY.MEDIUM },
{ term: 'chal be', severity: SEVERITY.LOW },
{ term: 'chal be saale', severity: SEVERITY.MEDIUM },
{ term: 'chal be kamine', severity: SEVERITY.MEDIUM },
{ term: 'abe hatt', severity: SEVERITY.LOW },
{ term: 'abe chal', severity: SEVERITY.LOW },
{ term: 'oye hatt', severity: SEVERITY.LOW },
{ term: 'oye chal', severity: SEVERITY.LOW },
{ term: 'bakwas aadmi', severity: SEVERITY.LOW },
{ term: 'bakwas banda', severity: SEVERITY.LOW },
{ term: 'bakwas insaan', severity: SEVERITY.LOW },
{ term: 'bekaar insaan', severity: SEVERITY.LOW },
{ term: 'ghatiya banda', severity: SEVERITY.MEDIUM },
{ term: 'ghatiya aadmi', severity: SEVERITY.MEDIUM },
{ term: 'ghatiya insaan', severity: SEVERITY.MEDIUM },
{ term: 'ghatiya soch wala', severity: SEVERITY.MEDIUM },
{ term: 'ghatiya soch wali', severity: SEVERITY.MEDIUM },
{ term: 'gandi soch', severity: SEVERITY.LOW },
{ term: 'ganda aadmi', severity: SEVERITY.MEDIUM },
{ term: 'gandi aurat', severity: SEVERITY.MEDIUM },
{ term: 'ganda banda', severity: SEVERITY.MEDIUM },
{ term: 'gandi harkat', severity: SEVERITY.LOW },
{ term: 'gandi harkatein', severity: SEVERITY.LOW },
{ term: 'ghatiya harkat', severity: SEVERITY.MEDIUM },
{ term: 'ghatiya harkatein', severity: SEVERITY.MEDIUM },
{ term: 'sharmnaak harkat', severity: SEVERITY.LOW },
{ term: 'bakwaas harkat', severity: SEVERITY.LOW },
{ term: 'cheap aadmi', severity: SEVERITY.LOW },
{ term: 'cheap banda', severity: SEVERITY.LOW },
{ term: 'cheap insaan', severity: SEVERITY.LOW },
{ term: 'cheap mentality', severity: SEVERITY.MEDIUM },
{ term: 'cheap mindset', severity: SEVERITY.MEDIUM },
{ term: 'low mentality', severity: SEVERITY.LOW },
{ term: 'low class behaviour', severity: SEVERITY.MEDIUM },
{ term: 'third class aadmi', severity: SEVERITY.MEDIUM },
{ term: 'third class banda', severity: SEVERITY.MEDIUM },
{ term: 'third class insaan', severity: SEVERITY.MEDIUM },
{ term: 'ghatiya level', severity: SEVERITY.LOW },
{ term: 'neech harkat', severity: SEVERITY.MEDIUM },
{ term: 'neech aadmi', severity: SEVERITY.MEDIUM },
{ term: 'neech banda', severity: SEVERITY.MEDIUM },
{ term: 'neech soch', severity: SEVERITY.MEDIUM },
{ term: 'girahua insaan', severity: SEVERITY.MEDIUM },
{ term: 'girahua aadmi', severity: SEVERITY.MEDIUM },
{ term: 'girahua banda', severity: SEVERITY.MEDIUM },
{ term: 'zaleel aadmi', severity: SEVERITY.MEDIUM },
{ term: 'zaleel banda', severity: SEVERITY.MEDIUM },
{ term: 'zaleel insaan', severity: SEVERITY.MEDIUM },
{ term: 'beghairat aadmi', severity: SEVERITY.MEDIUM },
{ term: 'beghairat banda', severity: SEVERITY.MEDIUM },
{ term: 'beghairat insaan', severity: SEVERITY.MEDIUM },
{ term: 'sharam bech di', severity: SEVERITY.MEDIUM },
{ term: 'gairat bech di', severity: SEVERITY.MEDIUM },
{ term: 'izzat nahi hai', severity: SEVERITY.LOW },
{ term: 'izzat ka naam nahi', severity: SEVERITY.LOW },
{ term: 'aukaat dikha di', severity: SEVERITY.LOW },
{ term: 'aukaat samajh', severity: SEVERITY.MEDIUM },
{ term: 'apni limit mein reh', severity: SEVERITY.LOW },
{ term: 'limit cross mat kar', severity: SEVERITY.LOW },
{ term: 'had mein reh', severity: SEVERITY.LOW },
{ term: 'had paar mat kar', severity: SEVERITY.LOW },
{ term: 'zyada hero mat ban', severity: SEVERITY.LOW },
{ term: 'hero banne ki zarurat nahi', severity: SEVERITY.LOW },
{ term: 'hero mat ban', severity: SEVERITY.LOW },
{ term: 'oversmart mat ban', severity: SEVERITY.LOW },
{ term: 'oversmart aadmi', severity: SEVERITY.LOW },
{ term: 'smartass', severity: SEVERITY.MEDIUM },
{ term: 'smartass idiot', severity: SEVERITY.MEDIUM },
{ term: 'wise guy', severity: SEVERITY.LOW },
{ term: 'know it all', severity: SEVERITY.LOW },
{ term: 'know it all idiot', severity: SEVERITY.MEDIUM },
{ term: 'attention seeker', severity: SEVERITY.LOW },
{ term: 'clout chaser', severity: SEVERITY.LOW },
{ term: 'clout hungry', severity: SEVERITY.LOW },
{ term: 'fake flexer', severity: SEVERITY.LOW },
{ term: 'show off', severity: SEVERITY.LOW },
{ term: 'showoff idiot', severity: SEVERITY.MEDIUM },
{ term: 'fake flex', severity: SEVERITY.LOW },
{ term: 'overconfident idiot', severity: SEVERITY.MEDIUM },
{ term: 'arrogant idiot', severity: SEVERITY.MEDIUM },
{ term: 'arrogant bastard', severity: SEVERITY.MEDIUM },
{ term: 'self centered idiot', severity: SEVERITY.MEDIUM },
{ term: 'selfish bastard', severity: SEVERITY.MEDIUM },
{ term: 'greedy bastard', severity: SEVERITY.MEDIUM },
{ term: 'cheap bastard', severity: SEVERITY.MEDIUM },
{ term: 'dirty minded', severity: SEVERITY.MEDIUM },
{ term: 'dirty minded idiot', severity: SEVERITY.MEDIUM },
{ term: 'dirty minded bastard', severity: SEVERITY.MEDIUM },
{ term: 'pervy idiot', severity: SEVERITY.MEDIUM },
{ term: 'pervy bastard', severity: SEVERITY.MEDIUM },
{ term: 'creepy dude', severity: SEVERITY.MEDIUM },
{ term: 'creepy guy', severity: SEVERITY.MEDIUM },
{ term: 'creepy girl', severity: SEVERITY.MEDIUM },
{ term: 'creepy person', severity: SEVERITY.MEDIUM },
{ term: 'weird dude', severity: SEVERITY.LOW },
{ term: 'weird guy', severity: SEVERITY.LOW },
{ term: 'weird girl', severity: SEVERITY.LOW },
{ term: 'weird person', severity: SEVERITY.LOW },
{ term: 'strange idiot', severity: SEVERITY.LOW },
{ term: 'annoying dude', severity: SEVERITY.LOW },
{ term: 'annoying guy', severity: SEVERITY.LOW },
{ term: 'annoying girl', severity: SEVERITY.LOW },
{ term: 'annoying person', severity: SEVERITY.LOW },
{ term: 'irritating dude', severity: SEVERITY.LOW },
{ term: 'irritating guy', severity: SEVERITY.LOW },
{ term: 'irritating person', severity: SEVERITY.LOW },
{ term: 'useless dude', severity: SEVERITY.MEDIUM },
{ term: 'useless guy', severity: SEVERITY.MEDIUM },
{ term: 'useless person', severity: SEVERITY.MEDIUM },
{ term: 'pathetic dude', severity: SEVERITY.MEDIUM },
{ term: 'pathetic guy', severity: SEVERITY.MEDIUM },
{ term: 'pathetic person', severity: SEVERITY.MEDIUM },
{ term: 'worthless dude', severity: SEVERITY.MEDIUM },
{ term: 'worthless guy', severity: SEVERITY.MEDIUM },
{ term: 'worthless person', severity: SEVERITY.MEDIUM },
{ term: 'trash human', severity: SEVERITY.MEDIUM },
{ term: 'trash person', severity: SEVERITY.MEDIUM },
{ term: 'garbage human', severity: SEVERITY.MEDIUM },
{ term: 'garbage person', severity: SEVERITY.MEDIUM },
{ term: 'human garbage', severity: SEVERITY.MEDIUM },
{ term: 'absolute trash', severity: SEVERITY.MEDIUM },
{ term: 'complete trash', severity: SEVERITY.MEDIUM },
{ term: 'total garbage', severity: SEVERITY.MEDIUM },
{ term: 'absolute idiot', severity: SEVERITY.MEDIUM },
{ term: 'complete idiot', severity: SEVERITY.MEDIUM },
{ term: 'total idiot', severity: SEVERITY.MEDIUM },
{ term: 'absolute moron', severity: SEVERITY.MEDIUM },
{ term: 'complete moron', severity: SEVERITY.MEDIUM },
{ term: 'total moron', severity: SEVERITY.MEDIUM },
{ term: 'absolute loser', severity: SEVERITY.MEDIUM },
{ term: 'complete loser', severity: SEVERITY.MEDIUM },
{ term: 'total loser', severity: SEVERITY.MEDIUM },
{ term: 'absolute asshole', severity: SEVERITY.HIGH },
{ term: 'complete asshole', severity: SEVERITY.HIGH },
{ term: 'total asshole', severity: SEVERITY.HIGH },
{ term: 'absolute bastard', severity: SEVERITY.MEDIUM },
{ term: 'complete bastard', severity: SEVERITY.MEDIUM },
{ term: 'total bastard', severity: SEVERITY.MEDIUM },
{ term: 'absolute shithead', severity: SEVERITY.HIGH },
{ term: 'complete shithead', severity: SEVERITY.HIGH },
{ term: 'total shithead', severity: SEVERITY.HIGH },
  // Add real terms here as needed — one { term, severity } entry per
  // line, term in lowercase with no spaces. HIGH severity terms are
  // never auto-masked-and-forgotten by moderateText() below; they're
  // always additionally flagged for review, matching "do not blindly
  // treat every bad word identically."
]
